### ISSUE TITLE
Gatesgarth not included in layer.conf in the gatesgarth branch

### ISSUE THREAD

**Issue by kwdavidson** [TimesysGit/meta-timesys#3]
https://github.com/TimesysGit/meta-timesys/blob/801a256711c367a2efc74ae2094f843362589b62/conf/layer.conf#L22

**Comment by iancampbell** [comment]
This issue has been resolved with https://github.com/TimesysGit/meta-timesys/commit/8f6cd37bab700ac168f2c3444aee472c85da288b
