### ISSUE TITLE
hundreds of notification per day for new releases

### ISSUE THREAD

**Issue by jbmaillet** [TimesysGit/meta-timesys#9]
Stop your automation publishing several hundreds of release per day, like:

https://github.com/TimesysGit/meta-timesys/releases/tag/v1.14.0%2Bhonister

For people following the project, this result in hundreds of notification. I had to unsubscribe from all notification from your project.

**Comment by jbmaillet** [comment]
As I am writing this, you made 772 releases. This is meaningless.

**Comment by harish-bansal** [comment]
@jbmaillet - I apologize for spamming your inbox with release notifications. We have now published all previous releases that caused the issue. 
Moving forward, you will only receive notifications for the latest release.

**Comment by jbmaillet** [comment]
OK.
